# Generated by Django 5.2.1 on 2025-05-21 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_LUMINOVA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(default='Insumo', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='insumos'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_terminados'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='App_LUMINOVA.categoria'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_terminados', to='App_LUMINOVA.categoria'),
        ),
    ]
