# Generated by Django 5.2.1 on 2025-05-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_LUMINOVA', '0002_categoria_delete_usuario_alter_insumo_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias_insumos/')),
            ],
            options={
                'verbose_name': 'Categoría de Insumo',
                'verbose_name_plural': 'Categorías de Insumos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias_productos/')),
            ],
            options={
                'verbose_name': 'Categoría de Producto Terminado',
                'verbose_name_plural': 'Categorías de Productos Terminados',
            },
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='App_LUMINOVA.categoriainsumo'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_terminados', to='App_LUMINOVA.categoriaproductoterminado'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
