# Generated by Django 5.2.1 on 2025-05-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_LUMINOVA', '0003_categoriainsumo_categoriaproductoterminado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_orden', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20)),
                ('cantidad_prod', models.IntegerField()),
                ('cliente', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='App_LUMINOVA.estadoorden')),
                ('insumos_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='App_LUMINOVA.insumo')),
                ('nombre_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_productos_terminados', to='App_LUMINOVA.categoriaproductoterminado')),
                ('nombre_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_terminados', to='App_LUMINOVA.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_reporte', models.IntegerField()),
                ('fecha', models.DateField()),
                ('tipo_problema', models.CharField()),
                ('informe_reporte', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='sector_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_asignado', to='App_LUMINOVA.sectorasignado'),
        ),
    ]
